import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./_components/QueryClientProvider";
import ReduxToolkitProvider from "./_components/ReduxToolkitProvider";
import MainThemeProvider from "./_components/ThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <MainThemeProvider>
          <QueryProvider>
            <ReduxToolkitProvider>{children}</ReduxToolkitProvider>
          </QueryProvider>
        </MainThemeProvider>
      </body>
    </html>
  );
}
