export const fakeRoads = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      id: 1,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.32699912, 48.8566579],
          [2.329, 48.857],
          [2.333, 48.858],
          [2.337, 48.859],
        ],
      },
      properties: {
        highway: "primary",
        name: "Rue du Bac",
        surface: "asphalt",
        lanes: 2,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "12",
      },
    },
    {
      type: "Feature",
      id: 2,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.382319, 48.833875],
          [2.378, 48.836],
          [2.374, 48.838],
          [2.37, 48.84],
        ],
      },
      properties: {
        highway: "secondary",
        name: "Quai de Bercy",
        surface: "asphalt",
        lanes: 3,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "18",
      },
    },
    {
      type: "Feature",
      id: 3,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.29327722, 48.8759745],
          [2.296, 48.876],
          [2.299, 48.876],
          [2.302, 48.877],
        ],
      },
      properties: {
        highway: "primary",
        name: "Avenue Carnot",
        surface: "asphalt",
        lanes: 4,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "25",
      },
    },
    {
      type: "Feature",
      id: 4,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.309631, 48.875263],
          [2.312, 48.874],
          [2.315, 48.873],
          [2.318, 48.872],
        ],
      },
      properties: {
        highway: "primary",
        name: "Boulevard Haussmann",
        surface: "asphalt",
        lanes: 4,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "30",
      },
    },
    {
      type: "Feature",
      id: 5,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.349481, 48.8566],
          [2.352, 48.857],
          [2.355, 48.858],
          [2.358, 48.859],
        ],
      },
      properties: {
        highway: "tertiary",
        name: "Quai de Gesvres",
        surface: "asphalt",
        lanes: 2,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "15",
      },
    },
    {
      type: "Feature",
      id: 6,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.3246848, 48.8701243],
          [2.327, 48.869],
          [2.329, 48.868],
          [2.332, 48.867],
        ],
      },
      properties: {
        highway: "primary",
        name: "Place de la Madeleine",
        surface: "asphalt",
        lanes: 3,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "20",
      },
    },
    {
      type: "Feature",
      id: 7,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.298733, 48.861935],
          [2.301, 48.862],
          [2.304, 48.863],
          [2.307, 48.864],
        ],
      },
      properties: {
        highway: "secondary",
        name: "Quai Jacques Chirac",
        surface: "asphalt",
        lanes: 3,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "18",
      },
    },
    {
      type: "Feature",
      id: 8,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.375691, 48.845002],
          [2.378, 48.846],
          [2.381, 48.847],
          [2.384, 48.848],
        ],
      },
      properties: {
        highway: "trunk",
        name: "Rue de Chalon",
        surface: "asphalt",
        lanes: 4,
        maxspeed: "70",
        oneway: false,
        ref: null,
        width: "28",
      },
    },
    {
      type: "Feature",
      id: 9,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.253626, 48.845261],
          [2.256, 48.846],
          [2.259, 48.847],
          [2.262, 48.848],
        ],
      },
      properties: {
        highway: "secondary",
        name: "Rue Nungesser et Coli",
        surface: "asphalt",
        lanes: 2,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "14",
      },
    },
    {
      type: "Feature",
      id: 10,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.333569, 48.851193],
          [2.336, 48.852],
          [2.339, 48.853],
          [2.342, 48.854],
        ],
      },
      properties: {
        highway: "tertiary",
        name: "Place Saint Sulpice",
        surface: "asphalt",
        lanes: 2,
        maxspeed: "30",
        oneway: false,
        ref: null,
        width: "12",
      },
    },
    {
      type: "Feature",
      id: 11,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.29319, 48.87897],
          [2.296, 48.879],
          [2.299, 48.88],
          [2.302, 48.881],
        ],
      },
      properties: {
        highway: "primary",
        name: "Avenue des Ternes",
        surface: "asphalt",
        lanes: 4,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "25",
      },
    },
    {
      type: "Feature",
      id: 12,
      geometry: {
        type: "LineString",
        coordinates: [
          [2.285643, 48.833487],
          [2.288, 48.834],
          [2.291, 48.835],
          [2.294, 48.836],
        ],
      },
      properties: {
        highway: "primary",
        name: "Boulevard Victor",
        surface: "asphalt",
        lanes: 4,
        maxspeed: "50",
        oneway: false,
        ref: null,
        width: "24",
      },
    },
  ],
};
